### PR TITLE
24 modify notebooks and structure for run 2

### PR DESCRIPTION
**Pull request by davecash75**
I have reviewed all of the notebooks, moved the imaging and Git into additional resources, and simplified environments.

### CODE REVIEW

**Comment by davecash75** [comment]
@dpshelio is there anyone from ARC who can look over one file in particular, the Data_Wrangling_WHO.ipynb, as I have done the most on that.

**Comment by davecash75** [comment]
There is a bug in the EBM python code that the notebook references. I'm chasing up with authors.

**Comment by dpshelio** [comment]
@tim-band - would you be able to look at the `Data_Wrangling_WHO.ipynb` notebook and provide feedback? This is part of what will be used at Tem Coders next week.

**Comment by davecash75** [comment]
Bug with the kde-ebm code is fixed, so that should no longer be an issue.

**Comment by davecash75** [comment]
@dpshelio @tim-band would very much appreciate you looking at this, but in the interest of having it up and ready, I'm going to merge this pull request. By all means then have a look at the main branch and patch if you spot anything that needs to be changed!
Many thanks!
Dave

**Pull request merged**
