### PR TITLE
Made a RISE presentation out of the KDE notebooks

### PR DESCRIPTION
**Pull request by davecash75**
Also simplified the environment.yml a little bit.

### CODE REVIEW

**Comment by davecash75** [comment]
@mary-tziraki I've updated the KDE walkthrough notebook to have a slide version as I have done with the biomarker extraction. Let me know if you have time and you really want to review it, but otherwise I would suggest we just merge it.
This doesn't affect the main notebooks they are looking through, so I would suggest we don't have them sync their forked repos unless we have other important updates for them.

**Comment by mary-tziraki** [comment]
Hi Dave, 
Thank you 
Yes I’ll do it this evening 
Kind regards
Mary

**Comment by davecash75** [comment]
> git checkout -b kbe-rice

Just checking did you checkout a branch kbe-rice or kde-rise?

**Comment by davecash75** [comment]
Thanks Mary, all spelling changes added in. Will merge now.

**Pull request merged**
